### ISSUE TITLE
Using hybrid mode does not properly render when coming back from insert mode

### ISSUE THREAD

**Issue by devboy** [OXY2DEV/markview.nvim#93]
**Describe the bug**

**Are you using a distro?**
NVChad

>[!NOTE]
> Distros can sometimes cause unusual behavior due to changing various options.

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document.
3.  Enter insert mode
4. Leave insert mode

**Expected behavior**
Switches between rendered and non rendered mode

**Actual behavior**
Does not switch back to rendered mode, only for some reason when I enter command mode (`:`)

**Screenshots**

https://github.com/user-attachments/assets/70506766-edcf-4353-a76f-9713686f2e2f

**Neovim version**
0.10.1

**Additional context**
Config: 
```return {
  "OXY2DEV/markview.nvim",
  enabled = true,
  branch = "dev",
  lazy = false,
  cmd = { "Markview" },
  dependencies = {
    -- You may not need this if you don't lazy load
    -- Or if the parsers are in your $RUNTIMEPATH
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
  opts = {
    modes = { "n", "i", "no", "c" },
    hybrid_modes = { "i" },

    -- This is nice to have
    callbacks = {
      on_enable = function(_, win)
        vim.wo[win].conceallevel = 2
        vim.wo[win].conecalcursor = "nc"
      end,
    },
  },
}
```

**Comment by OXY2DEV** [comment]
This issue is fixed now

**Comment by devboy** [comment]
Thank you, can confirm this is working now (using main branch)

**Comment by devboy** [comment]
Partially actually, still see a few places where sections of the markdown do not get rerenderd.

**Comment by OXY2DEV** [comment]
> Partially actually, still see a few places where sections of the markdown do not get rerenderd.

Send screenshot

**Comment by OXY2DEV** [comment]
> Partially actually, still see a few places where sections of the markdown do not get rerenderd.

![Screenshot_2024-08-08-20-25-56-614_com termux-edit](https://github.com/user-attachments/assets/feefe182-6586-45ab-a6e6-5e480aaa1b19)


If you are talking about something like this then that's intended since otherwise it makes the feature next to impossible to use when editing.

**Comment by devboy** [comment]
Yep, looks good now. Thanks
